/* tslint:disable */
/* eslint-disable */
/**
 * SPClientMgmt
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, {AxiosInstance, AxiosRequestConfig, AxiosResponse} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {BASE_PATH, BaseAPI, COLLECTION_FORMATS, RequestArgs, RequiredError} from '../base';
import {ListResponseDTO, RequestFilterClientDTO} from '../models';

/**
 * ClientApi - axios parameter creator
 * @export
 */
export const ClientApiAxiosParamCreator = function (configuration?: Configuration) {
    return {

        /**
         * get all customers
         * @summary get all customers
         * @param {RequestFilterClientDTO} body Body filter client code in system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findClients: async (body: RequestFilterClientDTO, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling findClients.');
            }
            const localVarPath = `/clients/customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },

    }
};

/**
 * ClientApi - functional programming interface
 * @export
 */
export const ClientApiFp = function(configuration?: Configuration) {
    return {
        /**
         * get all customers
         * @summary get all customers
         * @param {RequestFilterClientDTO} body Body filter client code in system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findClients(body: RequestFilterClientDTO, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ListResponseDTO>>> {
            const localVarAxiosArgs = await ClientApiAxiosParamCreator(configuration).findClients(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },

    }
};

/**
 * ClientApi - factory interface
 * @export
 */
export const ClientApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
      /**
         * get all customers
         * @summary get all customers
         * @param {RequestFilterClientDTO} body Body filter client code in system
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findClients(body: RequestFilterClientDTO, options?: AxiosRequestConfig): Promise<AxiosResponse<ListResponseDTO>> {
            return ClientApiFp(configuration).findClients(body, options).then((request) => request(axios, basePath));
        },

    };
};

/**
 * ClientApi - object-oriented interface
 * @export
 * @class ClientApi
 * @extends {BaseAPI}
 */
export class ClientApi extends BaseAPI {
   /**
     * get all customers
     * @summary get all customers
     * @param {RequestFilterClientDTO} body Body filter client code in system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ClientApi
     */
    public async findClients(body: RequestFilterClientDTO, options?: AxiosRequestConfig) : Promise<AxiosResponse<ListResponseDTO>> {
        return ClientApiFp(this.configuration).findClients(body, options).then((request) => request(this.axios, this.basePath));
    }

}
